name: Render PlantUML to PNG

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**/*.puml'
      - '.github/workflows/plantuml.yml'
  pull_request:
    paths:
      - 'docs/**/*.puml'
      - '.github/workflows/plantuml.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PlantUML & Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml graphviz
          plantuml -version
          dot -V

      - name: Render all .puml under docs/ to PNG
        run: |
          mkdir -p docs/diagrams
          find docs -name "*.puml" -print0 | xargs -0 -I {} plantuml -tpng -o diagrams {}

      - name: Commit rendered images back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(plantuml): render .puml to PNG [skip ci]"
          file_pattern: docs/diagrams/**/*.png

